# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

helloWorld <- function() {
    .Call('_rTest_helloWorld', PACKAGE = 'rTest')
}

init <- function() {
    .Call('_rTest_init', PACKAGE = 'rTest')
}

simple_finalize <- function() {
    .Call('_rTest_simple_finalize', PACKAGE = 'rTest')
}

init_GlobalDefWriter <- function() {
    .Call('_rTest_init_GlobalDefWriter', PACKAGE = 'rTest')
}

globalDefWriter_WriteString <- function(stringRef, stringRefValue) {
    .Call('_rTest_globalDefWriter_WriteString', PACKAGE = 'rTest', stringRef, stringRefValue)
}

globalDefWriter_WriteRegion <- function(regionRef, stringRef_name) {
    .Call('_rTest_globalDefWriter_WriteRegion', PACKAGE = 'rTest', regionRef, stringRef_name)
}

evtWriter_Write <- function(regionRef, event_type) {
    .Call('_rTest_evtWriter_Write', PACKAGE = 'rTest', regionRef, event_type)
}

