# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' finalize_otf2_server
#' @return R_NilValue
NULL

#' Initialize static otf2 {archive} objs
#' @param archivePath Path to the archive i.e. the directory where the anchor file is located.
#' @param archiveName Name of the archive. It is used to generate sub paths e.g. "archiveName.otf2"
#' @return R_NilValue
NULL

#' Close static otf2 {archive} objs
NULL

#' Initialize static otf2 {evt_writers} objs
NULL

#' Close static otf2 {evt_writers} objs
NULL

#' Enable or disable event measurement
#' @param measurementMode True to enable, else disable
#' @return R_NilValue
NULL

#' Init static otf2 {globaldefwriter} obj
NULL

#' Finalize static otf2 {globaldefwriter} obj
#'     Write clock information before ending tracing
NULL

#' Define new id-value pair in globaldefwriter
#' @param stringRefValue String assigned to given id
#' @return NUM_STRINGREF 
NULL

#' globalDefWriter_WriteRegion
#'     Define new region description in global writer
#' @param stringRef_RegionName Name to be associated with region
#' @return regionRef id/index for string
NULL

#' Write the system tree including a definition for the location group to the global definition writer.
#' @param stringRef_name Name to be associated with SystemTreeNode (eg MyHost)
#' @param stringRef_class Class to be associated with SystemTreeNode (eg node)
NULL

#' Write a definition for the location to the global definition writer.
NULL

#' Fork and initialize zeromq sockets for writing globalDef definitions
#' @param max_nprocs Maximum number of R processes (ie evtWriters required)
#' @param archivePath Path to otf2 archive
#' @param archiveName Name of otf2 archive
#' @return R_NilValue
init_otf2_logger <- function(max_nprocs, archivePath = "./rTrace", archiveName = "rTrace") {
    .Call('_rTrace_init_otf2_logger', PACKAGE = 'rTrace', max_nprocs, archivePath, archiveName)
}

#' finalize_GlobalDefWriter_client
#' @return RNilValue
finalize_GlobalDefWriter_client <- function() {
    .Call('_rTrace_finalize_GlobalDefWriter_client', PACKAGE = 'rTrace')
}

#' define_otf2_event_client
#' @param func_name Name of function to create event for
#' @return regionRef regionRef for use when logging events
define_otf2_event_client <- function(func_name) {
    .Call('_rTrace_define_otf2_event_client', PACKAGE = 'rTrace', func_name)
}

#' finalize_EvtWriter_client
#' @return R_NilValue
finalize_EvtWriter_client <- function() {
    .Call('_rTrace_finalize_EvtWriter_client', PACKAGE = 'rTrace')
}

#' finalize_otf2_client
#' @return R_NilValue
finalize_otf2_client <- function() {
    .Call('_rTrace_finalize_otf2_client', PACKAGE = 'rTrace')
}

#' Enable or disable event measurement
#' @param measurementMode True to enable, else disable
#' @return R_NilValue
evtWriter_MeasurementOnOff_client <- function(measurementMode) {
    .Call('_rTrace_evtWriter_MeasurementOnOff_client', PACKAGE = 'rTrace', measurementMode)
}

#' close_EvtWriterSocket_client
#' @return R_NilValue
close_EvtWriterSocket_client <- function() {
    .Call('_rTrace_close_EvtWriterSocket_client', PACKAGE = 'rTrace')
}

#' open_EvtWriterSocket_client
#' @return R_NilValue
open_EvtWriterSocket_client <- function() {
    .Call('_rTrace_open_EvtWriterSocket_client', PACKAGE = 'rTrace')
}

#' Write event to evt_writer
#' @param regionRef Region id
#' @param event_type True for enter, False for leave region
#' @return R_NilValue
evtWriter_Write_client <- function(regionRef, event_type) {
    .Call('_rTrace_evtWriter_Write_client', PACKAGE = 'rTrace', regionRef, event_type)
}

#' set_locationRef
#' @param id ID value belonging to this R proc
#' @return R_NilValue
set_locationRef <- function(id) {
    .Call('_rTrace_set_locationRef', PACKAGE = 'rTrace', id)
}

#' get_locationRef
#' @return locationRef Proc number between 0,nprocs-1
get_locationRef <- function() {
    .Call('_rTrace_get_locationRef', PACKAGE = 'rTrace')
}

#' set_maxUsedLocationRef_client
#' @param nprocs Current number of active evtWriters/procs
#' @return maxUsedLocationRef Current maximum evtWriters which were active so far
set_maxUsedLocationRef_client <- function(nprocs) {
    .Call('_rTrace_set_maxUsedLocationRef_client', PACKAGE = 'rTrace', nprocs)
}

#' print_errnos
#' @return R_NilValue
print_errnos <- function() {
    .Call('_rTrace_print_errnos', PACKAGE = 'rTrace')
}

#' set_id
#' @param newid new id
#' @return R_NilValue
set_id <- function(newid) {
    .Call('_rTrace_set_id', PACKAGE = 'rTrace', newid)
}

#' get_id
#' @return id int
get_id <- function() {
    .Call('_rTrace_get_id', PACKAGE = 'rTrace')
}

#' get_pid
get_pid <- function() {
    .Call('_rTrace_get_pid', PACKAGE = 'rTrace')
}

#' get_tid
get_tid <- function() {
    .Call('_rTrace_get_tid', PACKAGE = 'rTrace')
}

#' get_ppid
get_ppid <- function() {
    .Call('_rTrace_get_ppid', PACKAGE = 'rTrace')
}

